"""Add OTP verification fields to User model

Revision ID: 285a1e13fcd5
Revises: 46e6e51ea047
Create Date: 2025-07-28 16:23:32.976023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285a1e13fcd5'
down_revision = '46e6e51ea047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
